// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNwNtLJYoczeW6Sx6LHOHLpoz2LB8H4js',
    appId: '1:558585058498:web:4217bccb8ba60e0486975b',
    messagingSenderId: '558585058498',
    projectId: 'skatequest-app',
    authDomain: 'skatequest-app.firebaseapp.com',
    storageBucket: 'skatequest-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnW28vGEoxPUBRJNlzvP8m4kMTJGdaohA',
    appId: '1:558585058498:android:cfc5be73cfa4274e86975b',
    messagingSenderId: '558585058498',
    projectId: 'skatequest-app',
    storageBucket: 'skatequest-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZi4AxRIKdYmsREFHYc0GZkXK05bGbCmc',
    appId: '1:558585058498:ios:49f370b431df469186975b',
    messagingSenderId: '558585058498',
    projectId: 'skatequest-app',
    storageBucket: 'skatequest-app.appspot.com',
    iosBundleId: 'com.example.skatequestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZi4AxRIKdYmsREFHYc0GZkXK05bGbCmc',
    appId: '1:558585058498:ios:49f370b431df469186975b',
    messagingSenderId: '558585058498',
    projectId: 'skatequest-app',
    storageBucket: 'skatequest-app.appspot.com',
    iosBundleId: 'com.example.skatequestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNwNtLJYoczeW6Sx6LHOHLpoz2LB8H4js',
    appId: '1:558585058498:web:ad672b0505a8861986975b',
    messagingSenderId: '558585058498',
    projectId: 'skatequest-app',
    authDomain: 'skatequest-app.firebaseapp.com',
    storageBucket: 'skatequest-app.appspot.com',
  );
}
